CREATE TABLE "CUSTOMERS" (
  "CUSTOMERID" INTEGER
, "CITYID" INTEGER
, "COUNTRYID" INTEGER
, "REGIONID" INTEGER
, "CUSTOMER" VARCHAR(50)
, "CITYNAME" VARCHAR(50)
, "COUNTRYNAME" VARCHAR(50)
, "REGIONNAME" VARCHAR(50)
,  PRIMARY KEY (CUSTOMERID)
);

CREATE TABLE "PRODUCTS" (
  "PRODUCTID" INTEGER
, "CATEGORYID" INTEGER
, "LINEID" INTEGER 
, "PRODUCTNAME" VARCHAR(50)
, "PRODUCTDESCRIPTION" VARCHAR(50)
, "CATEGORYNAME" VARCHAR(50)
, "CATEGORYDESCRIPTION" VARCHAR(50)
, "LINENAME" VARCHAR(50)
, "LINEDESCRIPTION" VARCHAR(50)
, "DISCONTINUED" INTEGER 
,  PRIMARY KEY (PRODUCTID)
);

CREATE TABLE "ORDERS" (
  "ORDERID" INTEGER 
, "PRODUCTID" INTEGER 
, "CUSTOMERID" INTEGER 
, "EMPLOYEEID" INTEGER 
, "ORDERPERIODID" INTEGER 
, "REQUIREDPERIODID" INTEGER 
, "SHIPPEDPERIODID" INTEGER 
, "SHIPPERID" INTEGER 
, "UNITPRICE" INTEGER 
, "QUANTITY" INTEGER 
, "DISCOUNT" INTEGER 
, "UNITSALES" BIGINT 
, "NETSALES" BIGINT 
, "UNITCOST" INTEGER 
, "COST" INTEGER
, PRIMARY KEY (ORDERID, PRODUCTID)
);
