/*
DROP VIEW "V_ORDERS";
*/

CREATE VIEW "V_ORDERS"
AS SELECT  
  C.CUSTOMER, 
  C.CITYNAME, 
  C.COUNTRYNAME, 
  C.REGIONNAME, 
  P.PRODUCTNAME, 
  P.CATEGORYNAME, 
  P.LINENAME, 
  O.ORDERID, 
  O.UNITPRICE, 
  O.QUANTITY, 
  O.DISCOUNT, 
  O.UNITSALES, 
  O.NETSALES, 
  O.UNITCOST, 
  O.COST
FROM    
  CUSTOMERS AS C,
  PRODUCTS  AS P,
  ORDERS    AS O
WHERE 
  C.CUSTOMERID = O.CUSTOMERID
  AND P.PRODUCTID = O.PRODUCTID
;
