
IMPORT FROM CSV FILE '/tmp/sample/data/customers.csv' INTO CUSTOMERS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ','
THREADS 20
BATCH 50000;

IMPORT FROM CSV FILE '/tmp/sample/data/products.csv' INTO PRODUCTS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ','
THREADS 20
BATCH 50000;

IMPORT FROM CSV FILE '/tmp/sample/data/orders.csv' INTO ORDERS
WITH RECORD DELIMITED BY '\n'
FIELD DELIMITED BY ','
THREADS 20
BATCH 50000;
